### ISSUE TITLE
Add #define to identify if module is in use

### ISSUE THREAD

**Issue by adamski** [martinfinke/ReaX#12]
I would like to know if this module is in use, so that I can add extra Reactive class extensions in another module. 

I was thinking something like `#define REAX_MODULE 1` in the main header.

**Comment by martinfinke** [comment]
Hi Adam, thanks for using ReaX! JUCE should generate this line in your `AppConfig.h`:

```cpp
#define JUCE_MODULE_AVAILABLE_reax                          1
```

So you can use that to check if the module is there (should work for any JUCE module). Would this help with what you're trying to do?

**Comment by adamski** [comment]
Ah yes, I was wondering if there was something like that already! Yes exactly what I'm after, thanks.

**Comment by martinfinke** [comment]
Great!
