### ISSUE TITLE
Reactive<Value> assignment

### ISSUE THREAD

**Issue by adamski** [martinfinke/ReaX#16]
I'm trying to assign a `Reactive<Value>` from a `Value` within an `AudioProcessorValueTreeState`.

From the API docs: 
> It's implicitly convertible from and to juce::Value

I can assign in the initialiser list, but that doesn't work as the `AudioProcessorValueTreeState` is null at that point. 

Assigning in the constructor results in a compiler error:

> use of overloaded operator '=' is ambiguous (with operand types 'Reactive\<juce::Value>' and 'juce::Value')

My code currently looks like: 

```cpp
Reactive<Value> syncModeValue = processorState->getParameterAsValue (Ids::syncMode);
```

**Comment by adamski** [comment]
I solved it by using `<Reactive<AudioProcessorValueTreeState>` instead, and then using the value with

```cpp
processorState->rx.parameterValue (Ids::syncMode.toString()))
```

**Comment by martinfinke** [comment]
> Assigning in the constructor results in a compiler error:

Thanks for the report! 👍 I've [added assignment to the develop branch](https://github.com/martinfinke/ReaX/pull/20). When you assign a `Reactive<Value>` from a `juce::Value`, it's like calling `referTo`. The `Reactive<Value>` refers to a different source from then on out.

**Comment by adamski** [comment]
Great, thanks for adding that
